spring.application.name=delivery-service

spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=x9F3rT6pQ2wE1nM8vB7yL4cJ5aH2dG9fK3sR7uX1wZ5=
jwt.expiration=86400000